language: csharp
solution: YearMonth.sln
install:
  - nuget restore YearMonth.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release YearMonth.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./YearMonthTest/bin/Release/YearMonthTest.dll