language: csharp
solution: YearMonth.sln
mono: none
dotnet: 2.0.0
dist: xenial
install:
  - dotnet restore YearMonth.sln
script:
  - ls
  - ls /usr/bin
  - MSBuild
  - MSBuild.exe
  - msbuild /p:Configuration=Release YearMonth.sln