language: csharp
solution: YearMonth.sln
mono: none
dotnet: 2.0.0
 install:
  - dotnet restore
#  - nuget restore YearMonth.sln
#  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release YearMonth.sln
#  - mono ./packages/xunit.runners.*/tools/xunit.console.clr4.exe ./YearMonthTest/bin/Release/YearMonthTest.dll